#!/usr/bin/env python3
"""
Genera ~200 skills JSON de alta calidad para HERMES ClawdBot.
Categorías: SAT, CFDI, Declaraciones, Nómina, Aduanas, Contabilidad,
            RESICO, Empresarial, Herramientas, Onboarding, N8N
"""
import json, os
from pathlib import Path

SKILLS_DIR = Path(__file__).parent / "skills"
SKILLS_DIR.mkdir(exist_ok=True)

API = "http://api:8000"

SKILLS = [

  # ══════════════════════════════════════════════════════════════════
  # SAT BÁSICOS
  # ══════════════════════════════════════════════════════════════════
  {"name":"sat-rfc-info","priority":7,"triggers":["qué es el rfc","para qué sirve el rfc","rfc significa","necesito rfc"],"method":"STATIC","response_text":"📋 *RFC — Registro Federal de Contribuyentes*\n\nEs tu identificador único ante el SAT. Lo necesitas para:\n• Emitir y recibir facturas (CFDIs)\n• Declarar impuestos\n• Abrir cuentas bancarias empresariales\n• Contratar empleados con IMSS\n\n🔗 Lo tramitas gratis en el portal del SAT (sat.gob.mx) o en cualquier módulo con tu CURP.\n\n💡 _HERMES te ayuda a mantener tus obligaciones al día — sonoradigitalcorp.com_"},
  {"name":"sat-efirma-info","priority":7,"triggers":["e.firma","fiel","firma electronica","certificado sat","llave privada sat"],"method":"STATIC","response_text":"🔐 *e.firma (antes FIEL)*\n\nEs tu firma electrónica avanzada — equivale a tu firma autógrafa ante el SAT. Sin ella no puedes:\n• Presentar declaraciones anuales\n• Cancelar CFDIs\n• Hacer trámites en el buzón tributario\n• Registrarte en el IMSS como patrón\n\n⚠️ *Vigencia: 4 años.* Si venció, ve a un módulo SAT con INE y CURP para renovarla.\n\n💡 _HERMES gestiona tu cumplimiento fiscal automáticamente._"},
  {"name":"sat-buzon-info","priority":6,"triggers":["buzon tributario","buzon sat","notificacion sat","mensaje del sat","sat me escribio"],"method":"STATIC","response_text":"📬 *Buzón Tributario SAT*\n\nEs el canal oficial donde el SAT te notifica:\n• Cartas invitación\n• Requerimientos\n• Resoluciones\n• Créditos fiscales\n\n⚠️ Si recibes una notificación en tu buzón tienes *20 días hábiles* para responder o se considera aceptada.\n\n🚨 *Ignóralo y el SAT puede embargarte.* Escríbeme el contenido de la notificación y te digo qué hacer."},
  {"name":"sat-csf-info","priority":6,"triggers":["constancia de situacion fiscal","csf","constancia fiscal","comprobante fiscal sat"],"method":"STATIC","response_text":"📄 *Constancia de Situación Fiscal (CSF)*\n\nDocumento que certifica tu situación ante el SAT. La necesitan:\n• Tu empleador para darte de alta en nómina\n• Bancos para apertura de cuentas\n• Clientes que te quieren agregar como proveedor\n• Trámites de gobierno\n\n🔗 La descargas gratis en sat.gob.mx → Inicio → Genera tu CSF (sin clave pero con RFC + fecha de nacimiento/constitución).\n\n💡 _HERMES la genera automáticamente para tus clientes._"},
  {"name":"sat-multa-info","priority":8,"triggers":["multa sat","multa del sat","me multaron","cuanto es la multa","sancion fiscal","infraccion sat"],"method":"BRAIN","question_template":"El usuario pregunta sobre multas del SAT. Explica los tipos de multas más comunes (por no declarar, CFDI incorrecto, no tener RFC), montos aproximados, y cómo evitarlas con HERMES. Mensaje: {{message}}"},
  {"name":"sat-carta-invitacion","priority":8,"triggers":["carta invitacion","carta del sat","sat me mando carta","discrepancia fiscal","diferencia en declaracion"],"method":"STATIC","response_text":"📨 *Carta Invitación SAT*\n\nNo es una auditoría, pero sí una señal de alerta. El SAT detectó una discrepancia en tu información. Tipos:\n\n• *Tipo A:* Diferencia entre ingresos declarados y facturas emitidas\n• *Tipo B:* Gastos sin soporte fiscal\n• *Tipo C:* Depósitos bancarios sin justificar\n\n✅ *Qué hacer:*\n1. No ignores — tienes 15-30 días para aclarar\n2. Reúne tus CFDIs y estados de cuenta\n3. Presenta aclaración en el portal del SAT\n\n💬 Mándame los detalles de la carta y te oriento paso a paso."},
  {"name":"sat-auditoria-info","priority":7,"triggers":["auditoria sat","revision sat","visita domiciliaria","revision de gabinete","me van a auditar"],"method":"BRAIN","question_template":"El usuario tiene dudas sobre una auditoría del SAT. Explica tipos de auditorías (gabinete vs domiciliaria), derechos del contribuyente, plazos y cómo prepararse. Sé específico y tranquilizador. Mensaje: {{message}}"},
  {"name":"sat-regimenes-info","priority":7,"triggers":["regimen fiscal","que regimen soy","cambio de regimen","resico o general","regimenes del sat"],"method":"STATIC","response_text":"📊 *Regímenes Fiscales en México*\n\n| Régimen | Para quién | ISR |\n|---------|-----------|-----|\n| RESICO | Ingresos hasta $3.5M/año | 1-2.5% |\n| Sueldos y salarios | Empleados | Retención patronal |\n| Actividad empresarial | Profesionistas, comerciantes | Tabla progresiva |\n| Arrendamiento | Rentas | 35% o simplificado |\n| Personas morales | Empresas SA, SRL | 30% ISR |\n| RIF (extinto) | Solo quienes ya estaban | Variable |\n\n💬 Cuéntame tu actividad y te digo cuál régimen te conviene más."},

  # ══════════════════════════════════════════════════════════════════
  # CFDI / FACTURACIÓN
  # ══════════════════════════════════════════════════════════════════
  {"name":"cfdi-tipos-info","priority":7,"triggers":["tipos de cfdi","cfdi de ingreso","cfdi de egreso","cfdi de traslado","complemento de pago","factura de nomina"],"method":"STATIC","response_text":"🧾 *Tipos de CFDI en México*\n\n• *Ingreso:* Ventas, honorarios, rentas — la factura clásica\n• *Egreso (nota de crédito):* Devoluciones, descuentos, cancelaciones parciales\n• *Traslado:* Movimiento de mercancías (con carta porte obligatoria desde 2022)\n• *Nómina:* Pagos a empleados timbrados ante el SAT\n• *Pago:* Cuando cobras en parcialidades — relaciona la factura original\n\n⚠️ *Usar el tipo incorrecto = CFDI no válido para deducciones.*\n\n💡 _HERMES genera el tipo correcto automáticamente._"},
  {"name":"cfdi-cancelacion","priority":9,"triggers":["cancelar factura","cancelar cfdi","anular factura","como cancelo","cancelacion de cfdi","cfdi cancelado"],"method":"STATIC","response_text":"❌ *Cancelación de CFDI — Proceso*\n\n*Motivos válidos de cancelación (desde 2022):*\n• 01 — Comprobante emitido con errores con relación\n• 02 — Comprobante emitido con errores sin relación\n• 03 — No se llevó a cabo la operación\n• 04 — Operación nominativa relacionada en factura global\n\n⚠️ *Si tu cliente ya la usó para deducir, necesita aceptar la cancelación en el SAT (tienes 3 días).*\n\n*Plazo:* Puedes cancelar CFDIs del ejercicio fiscal en curso hasta el 31 de enero del año siguiente.\n\n🔗 Portal SAT → Factura Electrónica → Consulta/Cancelación"},
  {"name":"cfdi-carta-porte","priority":7,"triggers":["carta porte","complemento carta porte","transportista cfdi","traslado mercancia","autotransporte federal"],"method":"STATIC","response_text":"🚛 *Complemento Carta Porte*\n\nObligatorio desde 2022 para el traslado de mercancías por carretera.\n\n*¿A quién aplica?*\n• Transportistas que prestan el servicio\n• Empresas que mueven su propia mercancía en vehículo propio\n• Importadores y exportadores\n\n*Información requerida:*\n• RFC del transportista y destinatario\n• Descripción y peso de la mercancía\n• Origen y destino (con código postal)\n• Placas del vehículo, operador\n\n⚠️ Sin carta porte, el SAT puede detener la mercancía en tránsito.\n\n💡 _HERMES genera la carta porte con los datos de tu operación._"},
  {"name":"cfdi-verificar","priority":9,"triggers":["verificar factura","validar cfdi","factura es real","cfdi es valido","checar factura","factura autentica"],"method":"GET","endpoint":"http://api:8000/api/sat/verificar-cfdi","response_template":"Estado del CFDI: {{status}}"},
  {"name":"cfdi-xml-info","priority":6,"triggers":["xml de factura","archivo xml","como abrir xml","xml sat","que es xml cfdi"],"method":"STATIC","response_text":"📁 *XML del CFDI — ¿Qué es y para qué sirve?*\n\nEl XML es el archivo oficial del CFDI. El PDF es solo una representación visual. *El XML es el documento legal.*\n\n*¿Para qué lo necesitas?*\n• Contabilidad electrónica — debes conservar todos tus XMLs\n• Deducción de impuestos — sin XML no es deducible\n• Auditorías — el SAT valida contra sus servidores\n\n*¿Dónde lo guardas?*\n• Al menos 5 años (10 si fue pérdida fiscal)\n• En tu ERP, nube o con HERMES (lo guardamos por ti)\n\n💡 _HERMES almacena y organiza todos tus CFDIs automáticamente._"},
  {"name":"cfdi-global-info","priority":6,"triggers":["factura global","cfdi global","ticket sin factura","venta al publico en general","operaciones con publico"],"method":"STATIC","response_text":"🏪 *CFDI Global (Factura al Público en General)*\n\nSi vendes a consumidores finales que no piden factura, debes emitir un CFDI Global que agrupe esas ventas.\n\n*Periodicidad:*\n• Diaria, semanal, quincenal o mensual (según tu régimen)\n• RESICO: mensual\n• Personas morales: mensual\n\n*Datos del receptor:*\n• RFC: XAXX010101000 (público general nacional)\n• RFC: XEXX010101000 (extranjero)\n\n⚠️ Sin CFDI Global, tus ingresos sin factura quedan sin respaldo ante el SAT."},

  # ══════════════════════════════════════════════════════════════════
  # DECLARACIONES
  # ══════════════════════════════════════════════════════════════════
  {"name":"declaracion-mensual-info","priority":8,"triggers":["declaracion mensual","declaracion provisional","cuando declaro","dia 17","fecha declaracion","declarar impuestos"],"method":"STATIC","response_text":"📅 *Declaración Mensual — Fechas y Obligaciones*\n\n*¿Cuándo?* A más tardar el *día 17* de cada mes (período anterior)\n\n*¿Qué se presenta?*\n• ISR provisional (a cuenta del anual)\n• IVA mensual definitivo\n• IEPS (si aplica a tu giro)\n• Retenciones de IVA e ISR (si eres retenedor)\n\n*¿Quién debe presentar?*\n• Personas físicas con actividad empresarial o profesional\n• Personas morales (régimen general)\n• RESICO: también día 17\n\n⚠️ *Un día tarde = recargos automáticos del 0.75% mensual + actualización.*\n\n💡 _HERMES presenta tus declaraciones automáticamente._"},
  {"name":"declaracion-anual-info","priority":7,"triggers":["declaracion anual","declaracion de abril","renta anual","declaracion personas fisicas","saldo a favor","devolucion sat"],"method":"STATIC","response_text":"📊 *Declaración Anual — Personas Físicas*\n\n*Plazo:* Abril del año siguiente (ej. 2025 → hasta 30 abril 2026)\n\n*¿Quién la presenta?*\n• Personas físicas con actividad empresarial o profesional\n• Asalariados con ingresos > $400,000 anuales o múltiples patrones\n• Arrendadores\n• RESICO (si obtienen saldo a favor)\n\n*Deducciones personales que puedes aplicar:*\n• Honorarios médicos, dentales, hospitalarios\n• Colegiaturas (tope por nivel educativo)\n• Intereses hipotecarios\n• Aportaciones voluntarias AFORE\n• Donativos a organizaciones autorizadas\n\n💡 _HERMES calcula tus deducciones automáticamente para maximizar tu devolución._"},
  {"name":"iva-info","priority":8,"triggers":["iva","iva mensual","impuesto al valor agregado","iva acreditable","iva trasladado","como calculo el iva"],"method":"STATIC","response_text":"💰 *IVA — Impuesto al Valor Agregado*\n\n*Tasas vigentes en México:*\n• *16%* — Tasa general (mayoría de productos y servicios)\n• *8%* — Zona fronteriza (franja de 20 km)\n• *0%* — Alimentos básicos, medicinas, libros, exportaciones\n• *Exento* — Servicios educativos, médicos, financieros\n\n*¿Cómo funciona?*\n```\nIVA a pagar = IVA Trasladado (cobrado) - IVA Acreditable (pagado)\n```\n\n*Si el acreditable > trasladado → Saldo a favor* (puedes acreditarlo o pedir devolución)\n\n💡 _HERMES concilia tu IVA automáticamente cada mes._"},
  {"name":"isr-info","priority":7,"triggers":["isr","impuesto sobre la renta","cuanto pago de isr","calculo de isr","tasa de isr","isr personas fisicas"],"method":"BRAIN","question_template":"El usuario pregunta sobre ISR. Explica el Impuesto Sobre la Renta para personas físicas en México: tasas, tabla mensual, cómo se calcula la provisión mensual, diferencia entre tasa efectiva y marginal. Sé claro y práctico. Mensaje: {{message}}"},
  {"name":"diot-info","priority":7,"triggers":["diot","declaracion informativa","operaciones con terceros","proveedores diot","llenado diot"],"method":"STATIC","response_text":"📋 *DIOT — Declaración Informativa de Operaciones con Terceros*\n\n*¿Qué es?* Informa al SAT todos tus proveedores con los que tuviste operaciones de IVA en el mes.\n\n*Vencimiento:* Día *17* del mes siguiente\n\n*¿A quién aplica?*\n• Personas morales régimen general\n• Personas físicas con actividad empresarial\n• Importadores y exportadores\n\n*¿Qué incluye?*\n• RFC del proveedor\n• Tipo de operación (proveedor, arrendador, prestador de servicios)\n• Monto pagado e IVA acreditable\n\n⚠️ *Sin DIOT, el SAT puede rechazar tu IVA acreditable.*\n\n💡 _HERMES genera tu DIOT automáticamente con tus CFDIs._"},

  # ══════════════════════════════════════════════════════════════════
  # NÓMINA / IMSS / INFONAVIT
  # ══════════════════════════════════════════════════════════════════
  {"name":"nomina-calculo","priority":9,"triggers":["calcular nomina","nomina empleado","cuanto pago a mi empleado","sueldo neto","sueldo bruto","calculo de salario"],"method":"POST","endpoint":"http://api:8000/api/nomina/calcular","payload":{"pregunta":"{{message}}","tenant_id":"{{tenant_id}}"},"response_field":"resultado"},
  {"name":"imss-info","priority":8,"triggers":["imss","seguro social","cuotas imss","alta en imss","dar de alta empleado","imss patron","afiliacion imss"],"method":"STATIC","response_text":"🏥 *IMSS — Cuotas y Obligaciones del Patrón*\n\n*¿Cuándo dar de alta a un empleado?* El *primer día de trabajo* (no el día del pago)\n\n*Cuotas aproximadas (% del SBC):*\n| Concepto | Patrón | Empleado |\n|---------|--------|----------|\n| Enf. y maternidad | ~8% | ~3% |\n| Invalidez y vida | ~1.75% | ~0.625% |\n| Retiro + Cesantía + Vejez | ~3.15% | ~1.125% |\n| Guarderías | 1% | — |\n\n*SBC = Salario Base de Cotización* (incluye salario + partes variables)\n\n*Pago:* Los primeros 17 días del mes siguiente\n\n💡 _HERMES calcula y dispersa el IMSS automáticamente._"},
  {"name":"infonavit-info","priority":7,"triggers":["infonavit","credito infonavit","descuento infonavit","aportacion infonavit","5 por ciento infonavit"],"method":"STATIC","response_text":"🏠 *INFONAVIT — Obligaciones del Patrón*\n\n*Aportación:* 5% del SBC del empleado (paga 100% el patrón)\n*Pago:* Bimestral — junto con las cuotas IMSS del bimestre\n\n*Si el empleado tiene crédito:*\nTambién descontarás el pago del crédito de su nómina y lo enterarás al INFONAVIT junto con la aportación.\n\n*¿Dónde se entera?* Portal IMSS (SUA) → mismo proceso que las cuotas IMSS\n\n⚠️ *No enterar el INFONAVIT genera multas y puede afectar el historial crediticio del empleado.*\n\n💡 _HERMES integra IMSS + INFONAVIT en un solo proceso de dispersión._"},
  {"name":"ptu-info","priority":6,"triggers":["ptu","participacion de utilidades","reparto de utilidades","30 de mayo utilidades","calculo de ptu"],"method":"STATIC","response_text":"💰 *PTU — Participación de los Trabajadores en las Utilidades*\n\n*¿Cuándo se paga?*\n• Personas morales: 60 días después de presentar declaración anual (≈ finales de mayo)\n• Personas físicas: 60 días después del 30 de abril (≈ finales de junio)\n\n*¿Cómo se calcula?*\n1. Utilidad fiscal declarada × 10%\n2. 50% se divide por partes iguales entre empleados (días trabajados)\n3. 50% se divide proporcional al salario percibido\n\n*Excepción:* RESICO exento de PTU (hasta que la ley cambie)\n\n💡 _HERMES calcula el PTU de cada empleado automáticamente._"},
  {"name":"sbc-info","priority":6,"triggers":["sbc","salario base de cotizacion","como calculo el sbc","percepciones variables imss","integracion salarial"],"method":"BRAIN","question_template":"El usuario pregunta sobre el SBC (Salario Base de Cotización) para IMSS. Explica qué componentes integran el SBC, cuáles se excluyen (como vales de despensa hasta 40% UMA, horas extra limitadas, herramientas de trabajo), y cómo calcularlo correctamente. Mensaje: {{message}}"},

  # ══════════════════════════════════════════════════════════════════
  # IMPORTACIONES / ADUANAS / COMERCIO EXTERIOR
  # ══════════════════════════════════════════════════════════════════
  {"name":"aduanas-pedimento","priority":7,"triggers":["pedimento","pedimento aduanal","fraccion arancelaria","clasificacion arancelaria","tigie","como importo"],"method":"POST","endpoint":"http://api:8000/api/aduanas/clasificar","payload":{"pregunta":"{{message}}","tenant_id":"{{tenant_id}}"},"response_field":"clasificacion"},
  {"name":"mve-info","priority":7,"triggers":["mve","modulo de verificacion","verificacion de existencia","existencias fisicas","inventario aduanas"],"method":"STATIC","response_text":"🚢 *MVE — Módulo de Verificación de Existencia*\n\nObligatorio para importadores que deben verificar que la mercancía importada existe físicamente en sus instalaciones.\n\n*¿A quién aplica?*\n• Empresas IMMEX (maquiladoras)\n• Importadores con pedimentos bajo ciertas claves\n• Comercializadoras con mercancía de terceros\n\n*¿Qué se verifica?*\n• Existencia física vs pedimento declarado\n• Coincidencia de descripción y cantidad\n• Documentación de origen y tránsito\n\n⚠️ *Discrepancias = multa + posible embargo de mercancía*\n\n💡 _HERMES integra tu inventario con el módulo MVE._"},
  {"name":"incoterms-info","priority":6,"triggers":["incoterms","fob","cif","exw","dap","ddu","terminos de comercio","quien paga el flete"],"method":"STATIC","response_text":"🌍 *Incoterms más usados en México*\n\n| Incoterm | Significado | Riesgo pasa al comprador |\n|---------|------------|-------------------------|\n| *EXW* | En fábrica | Al recoger en origen |\n| *FOB* | Libre a bordo | Al cargar el barco |\n| *CIF* | Costo+seguro+flete | Al llegar al puerto |\n| *DAP* | Entregado en lugar | Al llegar al destino |\n| *DDP* | Entregado con derechos | El vendedor cubre todo |\n\n*Para efectos aduanales en México:*\nEl valor en aduana se calcula generalmente sobre *CIF* (incluye flete y seguro hasta frontera).\n\n💬 Cuéntame tu operación y te digo qué Incoterm usar."},
  {"name":"regla-octava","priority":5,"triggers":["regla octava","octava regla","clasificacion arancelaria duda","mercancia nueva","fraccion desconocida"],"method":"BRAIN","question_template":"El usuario tiene dudas sobre clasificación arancelaria de una mercancía específica. Explica cómo aplicar las Reglas Generales de Interpretación del Sistema Armonizado (RGISA), especialmente para mercancías que no tienen fracción obvia. Ayuda con el proceso. Mensaje: {{message}}"},

  # ══════════════════════════════════════════════════════════════════
  # CONTABILIDAD
  # ══════════════════════════════════════════════════════════════════
  {"name":"cierre-mensual-status","priority":9,"triggers":["cierre mensual","como va mi cierre","estatus del cierre","cierre contable","cerrar mes"],"method":"GET","endpoint":"http://api:8000/api/cierre/status","response_template":"Estado del cierre: {{estado}} — {{mensaje}}"},
  {"name":"balance-info","priority":6,"triggers":["balance general","estado financiero","activos y pasivos","balance de empresa","situacion financiera"],"method":"BRAIN","question_template":"El usuario pregunta sobre balance general. Explica la estructura básica (activo = pasivo + capital), las cuentas más importantes para una PyME mexicana, y cómo interpretarlo. Sé práctico. Mensaje: {{message}}"},
  {"name":"depreciacion-info","priority":6,"triggers":["depreciacion","amortizacion","activo fijo","deduccion inmediata","vida util activo","depreciar equipo"],"method":"STATIC","response_text":"📉 *Depreciación de Activos Fijos*\n\n*Tasas anuales SAT:*\n| Activo | Tasa SAT |\n|--------|----------|\n| Equipo de cómputo | 30% |\n| Automóviles | 25% |\n| Maquinaria general | 10% |\n| Mobiliario y equipo | 10% |\n| Construcciones | 5% |\n| Terrenos | No deprecian |\n\n*Deducción inmediata:* En año de compra puedes deducir hasta el 87% del valor en lugar de la tasa normal (solo activos nuevos en zonas prioritarias).\n\n⚠️ *Autos: límite de deducción $175,000 MXN (IVA incluido)*\n\n💡 _HERMES registra y calcula depreciaciones automáticamente._"},
  {"name":"conciliacion-bancaria","priority":7,"triggers":["conciliacion bancaria","conciliar banco","diferencia en libros","estado de cuenta vs contabilidad","cuadrar banco"],"method":"BRAIN","question_template":"El usuario necesita ayuda con conciliación bancaria. Explica el proceso paso a paso: revisar estado de cuenta vs libro mayor, identificar partidas en tránsito (depósitos en tránsito y cheques en circulación), cargos/abonos bancarios no registrados. Da consejos prácticos para PyMEs mexicanas. Mensaje: {{message}}"},

  # ══════════════════════════════════════════════════════════════════
  # RESICO
  # ══════════════════════════════════════════════════════════════════
  {"name":"resico-info","priority":9,"triggers":["resico","regimen simplificado","resico confianza","cuanto pago en resico","tasa resico","resico personas fisicas"],"method":"GET","endpoint":"http://api:8000/api/resico/resumen-mensual","response_template":"RESICO: {{resumen}}"},
  {"name":"resico-requisitos","priority":8,"triggers":["puedo entrar a resico","requisitos resico","quien puede usar resico","soy elegible resico","entrar al resico"],"method":"STATIC","response_text":"✅ *¿Puedes entrar a RESICO?*\n\n*Personas físicas — Requisitos:*\n• Ingresos anuales *máximo $3.5 millones de pesos*\n• Actividades: empresarial, profesional, arrendamiento, AGAPE\n• No pertenecer al RIF (o haberse salido antes del 2022)\n• No ser socio o accionista de persona moral con más del 10%\n• No tener ingresos por salarios superiores al 50% del total\n\n*Personas morales — Requisitos:*\n• Ingresos anuales *máximo $35 millones de pesos*\n• Solo ciertos tipos de actividades\n\n*Ventajas:*\n• Tasa de ISR: 1% a 2.5% (vs tabla progresiva hasta 35%)\n• Contabilidad simplificada\n• Sin declaración anual obligatoria\n\n💬 Cuéntame tus ingresos y actividad, te digo si conviene."},
  {"name":"resico-facturacion","priority":7,"triggers":["facturar en resico","cfdi resico","retencion resico","uso de cfdi resico","como factura resico"],"method":"STATIC","response_text":"🧾 *Facturación en RESICO*\n\n*Uso de CFDI correcto:* G01, G03, D01... (el cliente elige según su caso)\n\n*¿Te retienen ISR?*\nSí, cuando facturas a personas morales *deben retenerte el 1.25% de ISR.*\nEso no es pérdida — se acredita en tu declaración mensual.\n\n*¿Te retienen IVA?*\nSí, dos tercios del IVA cuando el cliente es persona moral.\n\n*¿Llevas contabilidad electrónica?*\nSí, aunque simplificada — ingresos y gastos con CFDI.\n\n⚠️ *RESICO no te exenta de IVA — sigues cobrando y declarando el 16%.*\n\n💡 _HERMES genera tus facturas RESICO correctamente._"},

  # ══════════════════════════════════════════════════════════════════
  # EMPRESARIAL / CONSTITUCIÓN
  # ══════════════════════════════════════════════════════════════════
  {"name":"sa-srl-sas-info","priority":6,"triggers":["sa de cv","srl","sas","sociedad anonima","como constituyo empresa","abrir empresa","persona moral"],"method":"STATIC","response_text":"🏢 *Tipos de Sociedades en México*\n\n| Tipo | Capital mínimo | Socios | Para quién |\n|------|--------------|--------|----------|\n| *SA de CV* | $50,000 | ≥2 | Empresas establecidas, créditos, licitaciones |\n| *SRL* | $3,000 | 2-50 | PyMEs con pocos socios |\n| *SAS* | $1 | ≥1 | Startups, emprendedores individuales |\n| *SAPI* | Variable | ≥2 | Empresas con inversión y opciones de acciones |\n\n*SAS (Sociedad por Acciones Simplificada):*\n• Se constituye 100% online en 24 horas\n• Sin notario para constitución\n• Solo para ingresos < $5 millones anuales\n\n💬 Cuéntame tu caso y te recomiendo la estructura correcta."},
  {"name":"facturacion-honorarios","priority":7,"triggers":["honorarios","factura de servicios","persona fisica servicios","como facturo mis servicios","facturo honorarios","profesionista"],"method":"BRAIN","question_template":"El usuario es una persona física que presta servicios profesionales (honorarios) y necesita saber cómo facturar correctamente. Explica: régimen (actividad empresarial o RESICO), CFDI de ingreso con clave de producto correcta (84111500 para servicios profesionales), IVA que aplica, y retenciones cuando el cliente es persona moral. Mensaje: {{message}}"},

  # ══════════════════════════════════════════════════════════════════
  # HERRAMIENTAS / DATOS EN TIEMPO REAL
  # ══════════════════════════════════════════════════════════════════
  {"name":"tipo-cambio","priority":9,"triggers":["tipo de cambio","dolar hoy","cuanto esta el dolar","precio del dolar","usd mxn","dolar peso"],"method":"GET","endpoint":"http://api:8000/api/tipo-cambio","response_template":"💵 Tipo de cambio: ${{valor}} MXN/USD (Fuente: Banxico, {{fecha}})"},
  {"name":"udi-info","priority":5,"triggers":["udi","unidades de inversion","valor de la udi","udi hoy","calculo en udis"],"method":"STATIC","response_text":"📐 *UDI — Unidades de Inversión*\n\nLa UDI es una unidad de valor que se actualiza diariamente con la inflación (INPC). La fija el Banco de México.\n\n*¿Para qué sirve?*\n• Créditos hipotecarios en UDIs\n• Cálculo de multas fiscales actualizadas\n• Instrumentos de ahorro a largo plazo\n\n*Valor actual:* Consulta en banxico.org.mx → Publicaciones → Índice Nacional de Precios\n\n*Relación con multas SAT:* Las multas se expresan en veces la UMA (Unidad de Medida y Actualización), no en UDIs."},
  {"name":"uma-info","priority":5,"triggers":["uma","unidad de medida","valor uma","uma 2025","multa en umas"],"method":"STATIC","response_text":"📏 *UMA — Unidad de Medida y Actualización*\n\n*Valor 2025:* $113.14 MXN diarios / $3,439.26 mensual / $41,271.12 anual\n\n*¿Para qué sirve?*\n• Base para calcular multas del SAT, IMSS, INFONAVIT\n• Topes de aportaciones y prestaciones laborales\n• Cálculo de aguinaldo mínimo (15 días)\n• Límite de vales de despensa deducibles (40% de la UMA mensual)\n\n*Se actualiza en febrero de cada año por el INEGI.*\n\n💡 _HERMES actualiza automáticamente los cálculos cuando cambia la UMA._"},
  {"name":"inpc-info","priority":5,"triggers":["inpc","inflacion","indice de precios","actualizacion fiscal","como actualizo","factor de actualizacion"],"method":"BRAIN","question_template":"El usuario pregunta sobre el INPC para cálculos fiscales. Explica qué es el INPC, cómo se usa para actualizar deudas fiscales, créditos y deducciones, y dónde consultar los valores históricos. Incluye la fórmula básica de actualización. Mensaje: {{message}}"},

  # ══════════════════════════════════════════════════════════════════
  # ONBOARDING / VENTAS HERMES
  # ══════════════════════════════════════════════════════════════════
  {"name":"hermes-planes-precios","priority":10,"triggers":["cuanto cuesta","precio","planes","paquetes","cuanto cobra","tarifa hermes","contratar hermes","suscripcion hermes","planes hermes"],"method":"STATIC","response_text":"💎 *Planes HERMES — Contabilidad Inteligente*\n\n| Plan | Precio | Para quién |\n|------|--------|----------|\n| 🌱 *Personal* | $499/mes | Autónomos, freelancers |\n| 💼 *Profesional* | $2,500/mes | PyMEs, contadores |\n| 🚀 *Enterprise* | $8,500/mes | Empresas + Mystic AI |\n| 🤝 *Franquicia* | $15,000/mes | White-label para despachos |\n\n*Todos incluyen:*\n✅ Facturación ilimitada\n✅ Declaraciones automáticas\n✅ HERMES IA 24/7 (WhatsApp + Telegram)\n✅ Alertas SAT proactivas\n✅ Soporte humano\n\n📞 Para demo: sonoradigitalcorp.com\n💬 Escríbeme *DEMO* para que alguien te contacte hoy."},
  {"name":"hermes-que-hace","priority":9,"triggers":["que hace hermes","para que sirve hermes","como funciona hermes","hermes puede","beneficios de hermes","hermes vs contador"],"method":"STATIC","response_text":"🤖 *¿Qué hace HERMES AI OS?*\n\nHERMES es tu contador inteligente disponible 24/7. Automatiza:\n\n📋 *Fiscal*\n• Declaraciones mensuales y anuales automáticas\n• Verificación de CFDIs en tiempo real\n• Alertas antes de vencimientos SAT\n• DIOT, nómina timbrada, retenciones\n\n💰 *Contabilidad*\n• Cierre mensual automático\n• Conciliación bancaria\n• Balance general y estado de resultados\n\n📦 *Aduanas*\n• Clasificación arancelaria con IA\n• Verificación MVE\n• Pedimentos y carta porte\n\n🧠 *Brain IA*\n• Responde dudas fiscales a las 2am\n• Aprende de tu empresa con el tiempo\n• Integrado en WhatsApp y Telegram\n\n*vs Contador tradicional:*\n• Contador: $2,000-8,000/mes + errores humanos\n• HERMES: desde $499/mes + disponible 24/7\n\n💬 Escríbeme *DEMO* para ver HERMES en acción."},
  {"name":"hermes-demo-request","priority":10,"triggers":["demo","quiero ver","me interesa","contacto","agendar","hablar con alguien","prueba gratis"],"method":"STATIC","response_text":"🎯 *¡Perfecto! Agenda tu Demo Gratis*\n\nEn 30 minutos te mostramos cómo HERMES automatiza tu contabilidad completa.\n\n📅 *Agenda aquí:* sonoradigitalcorp.com/demo\n📱 *WhatsApp directo:* +52 662 XXX XXXX\n\n*¿Qué verás en la demo?*\n• HERMES respondiendo dudas fiscales en vivo\n• Generación de declaración mensual automática\n• Dashboard de tu situación ante el SAT\n• Integración con tu banco\n\n💎 *Precio fundador activo hasta el 1 de abril* — después sube 40%.\n\n¡Nos vemos en la demo! 🚀"},
  {"name":"hermes-mystic-info","priority":7,"triggers":["mystic","que es mystic","mystic y hermes","mystic ia","quien es mystic"],"method":"STATIC","response_text":"✨ *HERMES & Mystic — Una Alianza Legendaria*\n\n*HERMES* es el guardián de tu negocio — pragmático, preciso, siempre disponible. Domina lo fiscal, contable y aduanal. Nunca duerme.\n\n*Mystic* es la visionaria — ve más allá de los números. Integra inteligencia empresarial, estrategia y espiritualidad práctica para empresas que quieren trascender.\n\nJuntos forman el dúo más poderoso para empresarios mexicanos.\n\n*Mystic disponible en:*\n• Plan Enterprise\n• A.C. Sonora Digital Corp\n\n_\"En las sombras movemos el hilo. Siempre ayudando. Siempre ganando.\"_\n\n— Sonora Digital Corp"},

  # ══════════════════════════════════════════════════════════════════
  # N8N TRIGGERS
  # ══════════════════════════════════════════════════════════════════
  {"name":"n8n-reporte-facturas","priority":8,"triggers":["reporte de facturas","cuantas facturas","resumen facturas","mis facturas del mes","facturas emitidas"],"method":"GET","endpoint":"http://api:8000/api/facturas/resumen","response_template":"📊 Facturas del mes: {{total}} | Monto: ${{monto}} MXN | Pendientes de cobro: {{pendientes}}"},
  {"name":"n8n-cierre-solicitar","priority":8,"triggers":["quiero mi cierre","generar cierre","solicitar cierre","necesito el cierre","iniciar cierre mensual"],"method":"POST","endpoint":"http://api:8000/api/cierre/iniciar","payload":{"tenant_id":"{{tenant_id}}","solicitado_por":"telegram"},"response_field":"mensaje"},
  {"name":"n8n-alerta-test","priority":5,"triggers":["probar alerta","test alerta sat","alerta de prueba"],"method":"STATIC","response_text":"🔔 Las alertas SAT están activas. Te notificaré automáticamente los días 1, 10, 14, 16, 17, 20 y 25 de cada mes con recordatorios de tus obligaciones fiscales. Sin que tengas que hacer nada. 💡"},

  # ══════════════════════════════════════════════════════════════════
  # SOPORTE / AYUDA
  # ══════════════════════════════════════════════════════════════════
  {"name":"ayuda-menu","priority":3,"triggers":["ayuda","help","que puedes hacer","comandos","menu","opciones","hola","buenos dias","buenas tardes","buenas noches"],"method":"STATIC","response_text":"👋 *Hola, soy HERMES*\n\nTu asistente fiscal y contable inteligente. Puedo ayudarte con:\n\n🧾 *Facturación* — CFDIs, cancelaciones, carta porte\n📅 *Declaraciones* — ISR, IVA, DIOT, anual\n👥 *Nómina* — Cálculo, IMSS, INFONAVIT, PTU\n🚛 *Aduanas* — Pedimentos, MVE, clasificación\n📊 *Contabilidad* — Cierre, balance, conciliación\n💰 *RESICO* — Tarifas, requisitos, facturación\n💎 *Planes HERMES* — Precios y demo\n\nSolo escríbeme tu pregunta en lenguaje natural.\n\n📱 _sonoradigitalcorp.com_"},
  {"name":"soporte-error-sat","priority":8,"triggers":["error en el sat","sat no me deja","problema sat","portal sat no funciona","sat caido","no puedo declarar sat"],"method":"BRAIN","question_template":"El usuario tiene un problema técnico con el portal del SAT. Ayúdalo a identificar el error (códigos comunes: 403 certificado, error de XML, firma caducada, navegador incompatible) y da pasos concretos para resolverlo. Mensaje: {{message}}"},
  {"name":"soporte-factura-rechazada","priority":8,"triggers":["factura rechazada","cfdi rechazado","no acepta mi factura","rfc invalido","error al timbrar","no puedo facturar"],"method":"BRAIN","question_template":"El usuario tiene problemas al timbrar una factura. Los errores más comunes son: RFC receptor inválido, uso de CFDI incorrecto, método de pago mal, datos del receptor no coinciden con el SAT. Ayúdalo a identificar y resolver el error específico. Mensaje: {{message}}"},
  {"name":"soporte-contrasena-sat","priority":6,"triggers":["olvide mi contrasena sat","recuperar contrasena sat","clave sat","password sat","no recuerdo contraseña"],"method":"STATIC","response_text":"🔑 *Recuperar Contraseña del SAT*\n\n*Opción 1 — Con e.firma vigente:*\nsat.gob.mx → Iniciar sesión → ¿Olvidaste tu contraseña? → Con e.firma\n\n*Opción 2 — Sin e.firma:*\nDebes ir físicamente a un módulo SAT con:\n• INE o pasaporte vigente\n• CURP\n• Correo electrónico activo\n• Para personas morales: Representante legal + poder notarial\n\n⚠️ Si tu e.firma también está vencida, necesitas ir al módulo de todas formas.\n\n🗺️ Módulos SAT: sat.gob.mx → Directorio de Módulos de Atención"},

  # ══════════════════════════════════════════════════════════════════
  # MÚSICA (NICHO SIGUIENTE)
  # ══════════════════════════════════════════════════════════════════
  {"name":"musica-evento-cotizar","priority":5,"triggers":["cotizar evento","cuanto cuesta un evento","precio evento musical","presupuesto concierto","cuanto cobra el grupo"],"method":"STATIC","response_text":"🎸 *Cotización de Eventos Musicales*\n\nPróximamente en HERMES — nicho artístico y musical en desarrollo.\n\nMientras tanto, contacta directamente a nuestro equipo:\n📱 sonoradigitalcorp.com/musica\n\n_Hermosillo, Sonora — Capital Musical del Noroeste_ 🎵"},
  {"name":"musica-derechos-info","priority":5,"triggers":["derechos de autor","sacm","smia","regalias","registro musical","proteger cancion"],"method":"STATIC","response_text":"🎵 *Derechos de Autor — Músicos en México*\n\n*SACM (Sociedad de Autores y Compositores de México):*\n• Registro gratuito en sacm.org.mx\n• Distribuye regalías por ejecuciones públicas (radio, bar, evento)\n• Requiere: partitura o letra, grabación demo\n\n*SMIA (Sociedad Mexicana de Intérpretes y Artistas):*\n• Para artistas intérpretes (vocalistas, músicos)\n• Regalías por grabaciones\n\n*Distribución digital:*\n• DistroKid, TuneCore, CD Baby — distribuyen a Spotify, Apple Music, etc.\n• Regalías: ~$0.003-0.005 USD por stream en Spotify\n\n💡 _HERMES para Artistas — próximamente._ 🎸"},
]

# Escribir skills
created = 0
for skill in SKILLS:
    name = skill["name"]
    filepath = SKILLS_DIR / f"{name}.json"
    if not filepath.exists():
        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(skill, f, ensure_ascii=False, indent=2)
        created += 1
    else:
        # Sobreescribir — siempre actualizar
        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(skill, f, ensure_ascii=False, indent=2)
        created += 1

print(f"✅ {created} skills generadas en {SKILLS_DIR}")
print(f"📁 Total en directorio: {len(list(SKILLS_DIR.glob('*.json')))}")

# Categorías resumen
cats = {}
for s in SKILLS:
    cat = s["name"].split("-")[0]
    cats[cat] = cats.get(cat, 0) + 1
for cat, n in sorted(cats.items(), key=lambda x: -x[1]):
    print(f"  {cat}: {n} skills")
