from .auth import router as auth_router
from .stats import router as stats_router
from .services import router as services_router
from .artists import router as artists_router
from .contact import router as contact_router
from .dashboard import router as dashboard_router
from .health import router as health_router
from .admin import router as admin_router
from .ai import router as ai_router
from .track import router as track_router
