server {
    listen 80;
    server_name calendario.aztrotech.mx;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    server_name calendario.aztrotech.mx;

    ssl_certificate /etc/letsencrypt/live/calendario.aztrotech.mx/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/calendario.aztrotech.mx/privkey.pem;

    location / {
        proxy_pass http://127.0.0.1:8901;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffering off;
        proxy_read_timeout 90s;
    }
}
