const http = require('http'); const FASTAPI = { host: '127.0.0.1', port: 8000 };
function api(method, path, body) { return new Promise((resolve) => { const data = body ? JSON.stringify(body) : null; const req = http.request({ hostname: FASTAPI.host, port: FASTAPI.port, path, method, headers: { 'Content-Type': 'application/json' }, timeout: 15000 }, (res) => { let d = ''; res.on('data', c => d += c); res.on('end', () => { try { resolve(JSON.parse(d)); } catch { resolve({ raw: d }); } }); }); req.on('error', (e) => resolve({ error: e.message })); if (data) req.write(data); req.end(); }); }
const tools = {
  app_register: { description: 'Registra un nuevo usuario en SDC App', inputSchema: { type: 'object', properties: { nombre: { type: 'string' }, email: { type: 'string' }, nicho: { type: 'string' }, plan: { type: 'string' } }, required: ['nombre', 'email', 'nicho'] }, handler: async (args) => await api('POST', '/app/register', args) },
  app_login: { description: 'Inicia sesión en SDC App', inputSchema: { type: 'object', properties: { email: { type: 'string' }, password: { type: 'string' } }, required: ['email', 'password'] }, handler: async (args) => await api('POST', '/app/login', args) },
  app_dashboard: { description: 'Obtiene dashboard personalizado de un usuario', inputSchema: { type: 'object', properties: { user_id: { type: 'string' } }, required: ['user_id'] }, handler: async (args) => await api('GET', `/app/dashboard/${args.user_id}`) },
  app_prompts: { description: 'Obtiene prompts disponibles por nicho', inputSchema: { type: 'object', properties: { nicho: { type: 'string' } }, required: ['nicho'] }, handler: async (args) => await api('GET', `/app/prompts/${args.nicho}`) },
  app_skills: { description: 'Obtiene skills disponibles por nicho', inputSchema: { type: 'object', properties: { nicho: { type: 'string' } }, required: ['nicho'] }, handler: async (args) => await api('GET', `/app/skills/${args.nicho}`) },
  app_execute: { description: 'Ejecuta una acción para un usuario', inputSchema: { type: 'object', properties: { user_id: { type: 'string' }, type: { type: 'string' }, name: { type: 'string' }, params: { type: 'object' } }, required: ['user_id', 'type', 'name'] }, handler: async (args) => await api('POST', `/app/execute/${args.user_id}`, { type: args.type, name: args.name, params: args.params || {} }) },
};
module.exports = { tools };
