const http = require('http'); const FASTAPI = { host: '127.0.0.1', port: 8000 };
function api(method, path, body) { return new Promise((resolve) => { const data = body ? JSON.stringify(body) : null; const req = http.request({ hostname: FASTAPI.host, port: FASTAPI.port, path, method, headers: { 'Content-Type': 'application/json' }, timeout: 15000 }, (res) => { let d = ''; res.on('data', c => d += c); res.on('end', () => { try { resolve(JSON.parse(d)); } catch { resolve({ raw: d }); } }); }); req.on('error', (e) => resolve({ error: e.message })); if (data) req.write(data); req.end(); }); }
const tools = {
  mysticverse_create_twin: { description: 'Crea un digital twin', inputSchema: { type: 'object', properties: {} }, handler: async (args) => await api('POST', '/api/mysticverse/twin', args) },
  mysticverse_get_twin: { description: 'Obtiene un digital twin', inputSchema: { type: 'object', properties: { twin_id: { type: 'string' } }, required: ['twin_id'] }, handler: async (args) => await api('GET', `/api/mysticverse/twin/${args.twin_id}`) },
  mysticverse_kyc_age: { description: 'Verifica edad KYC', inputSchema: { type: 'object', properties: { creator_id: { type: 'string' } }, required: ['creator_id'] }, handler: async (args) => await api('POST', '/api/mysticverse/kyc/age', args) },
  mysticverse_kyc_identity: { description: 'Verifica identidad KYC', inputSchema: { type: 'object', properties: { record_id: { type: 'string' } }, required: ['record_id'] }, handler: async (args) => await api('POST', `/api/mysticverse/kyc/identity/${args.record_id}`, args) },
  mysticverse_kyc_consent: { description: 'Firma consentimiento KYC', inputSchema: { type: 'object', properties: { record_id: { type: 'string' }, signature: { type: 'string' } }, required: ['record_id'] }, handler: async (args) => await api('POST', `/api/mysticverse/kyc/consent/${args.record_id}`, args) },
  mysticverse_kyc_status: { description: 'Estado de verificación KYC', inputSchema: { type: 'object', properties: { creator_id: { type: 'string' } }, required: ['creator_id'] }, handler: async (args) => await api('GET', `/api/mysticverse/kyc/status/${args.creator_id}`) },
  mysticverse_gamification_xp: { description: 'Añade XP a un jugador', inputSchema: { type: 'object', properties: { player_id: { type: 'string' }, amount: { type: 'number' }, reason: { type: 'string' } }, required: ['player_id'] }, handler: async (args) => await api('POST', '/api/mysticverse/gamification/xp', args) },
  mysticverse_gamification_action: { description: 'Trackea acción de jugador', inputSchema: { type: 'object', properties: { player_id: { type: 'string' }, action: { type: 'string' } }, required: ['player_id'] }, handler: async (args) => await api('POST', '/api/mysticverse/gamification/action', args) },
  mysticverse_gamification_login: { description: 'Login diario de jugador', inputSchema: { type: 'object', properties: { player_id: { type: 'string' } }, required: ['player_id'] }, handler: async (args) => await api('POST', '/api/mysticverse/gamification/login', args) },
  mysticverse_gamification_player: { description: 'Obtiene perfil de jugador', inputSchema: { type: 'object', properties: { player_id: { type: 'string' } }, required: ['player_id'] }, handler: async (args) => await api('GET', `/api/mysticverse/gamification/player/${args.player_id}`) },
  mysticverse_gamification_leaderboard: { description: 'Leaderboard de gamificación', inputSchema: { type: 'object', properties: { limit: { type: 'number' } } }, handler: async (args) => await api('GET', `/api/mysticverse/gamification/leaderboard?limit=${args.limit || 10}`) },
  mysticverse_gamification_badges: { description: 'Badges de un jugador', inputSchema: { type: 'object', properties: { player_id: { type: 'string' } }, required: ['player_id'] }, handler: async (args) => await api('GET', `/api/mysticverse/gamification/badges/${args.player_id}`) },
};
module.exports = { tools };
