#!/bin/bash
# Weekly Strategic Review — Auto-generates enterprise health report
set -euo pipefail

JARVIS_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
EVENTS="$JARVIS_HOME/state/logs/events.jsonl"
FIN_OPS="$JARVIS_HOME/state/finops.jsonl"
INITIATIVES_DIR="$JARVIS_HOME/sonora-enterprise-os/initiatives"
REPORTS_DIR="$JARVIS_HOME/state/reports"
SKILLS_LOG_DIR="$JARVIS_HOME/state/logs/skills"

mkdir -p "$REPORTS_DIR"

REPORT_DATE=$(date '+%Y-%m-%d')
WEEK_AGO=$(date -d '7 days ago' '+%Y-%m-%dT00:00:00Z')
REPORT_FILE="$REPORTS_DIR/weekly-${REPORT_DATE}.md"

python3 - <<PYEOF
import json, os, re
from datetime import datetime, timedelta, timezone
from collections import Counter, defaultdict

report_date = "${REPORT_DATE}"
week_ago_str = "${WEEK_AGO}"
week_ago = datetime.fromisoformat(week_ago_str.replace('Z', '+00:00'))

report_lines = []
report_lines.append(f"# Weekly Executive Review — {report_date}")
report_lines.append("")
report_lines.append(f"**Period**: {week_ago.strftime('%Y-%m-%d')} to {report_date}")
report_lines.append(f"**Generated by**: Strategy OS (weekly-review.sh)")
report_lines.append("")
report_lines.append("---")
report_lines.append("")

# ── Load events ────────────────────────────────────────
events = []
if os.path.exists("${EVENTS}"):
    with open("${EVENTS}") as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    ev = json.loads(line)
                    events.append(ev)
                except json.JSONDecodeError:
                    pass

# Filter last 7 days
recent_events = []
for ev in events:
    ts = ev.get("timestamp", "")
    try:
        ev_dt = datetime.fromisoformat(ts.replace('Z', '+00:00'))
        if ev_dt >= week_ago:
            recent_events.append(ev)
    except (ValueError, TypeError):
        pass

# Last 24h check
now = datetime.now(timezone.utc)
last_24h = [e for e in recent_events if
    (datetime.fromisoformat(e.get("timestamp", "").replace('Z', '+00:00')) if e.get("timestamp") else now) >= (now - timedelta(hours=24))]

# ── 1. Enterprise Score ────────────────────────────────
report_lines.append("## 1. Enterprise Score")
report_lines.append("")

finops_calls = []
if os.path.exists("${FIN_OPS}"):
    with open("${FIN_OPS}") as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    c = json.loads(line)
                    if c.get("event") == "ai_call":
                        finops_calls.append(c)
                except json.JSONDecodeError:
                    pass

def compute_score(evts, fcalls):
    revenue_evts = [e for e in evts if e.get("event") == "revenue_recorded"]
    revenue_score = min(10, len(revenue_evts)) if revenue_evts else 1

    scale_evts = [e for e in evts if e.get("event") in ("scaled_up", "scaled_down")]
    scalability_score = min(10, len(scale_evts) + 3)

    skill_evts = [e for e in evts if e.get("event") == "skill_execution"]
    os_used = set()
    for s in skill_evts:
        p = s.get("payload", {})
        if isinstance(p, dict):
            os_used.add(p.get("parent_os", ""))
    reusability_score = min(10, len(os_used))

    auto_evts = len(skill_evts)
    total_ops = len(evts)
    automation_score = min(10, round(auto_evts / max(1, total_ops) * 10)) if total_ops > 0 else 1

    knowledge_evts = [e for e in evts if e.get("event") == "knowledge_stored"]
    knowledge_score = min(10, len(knowledge_evts))

    healthy = len([e for e in evts if e.get("event") == "service_healthy"])
    down = len([e for e in evts if e.get("event") == "service_down"])
    total_health = healthy + down
    reliability_score = round(healthy / max(1, total_health) * 10) if total_health > 0 else 5

    recovered = len([e for e in evts if e.get("event") == "service_recovered"])
    total_incidents = down + recovered
    founder_score = min(10, round(recovered / max(1, total_incidents) * 10)) if total_incidents > 0 else 1

    event_types = len(set(e.get("event", "") for e in evts))
    simplicity_score = max(0, 10 - event_types // 10) if event_types > 0 else 10

    satisfaction_evts = [e for e in evts if e.get("event") == "satisfaction_recorded"]
    customer_score = min(10, len(satisfaction_evts)) if satisfaction_evts else 1

    total_cost = sum(c.get("cost", 0) for c in fcalls)
    total_calls = len(fcalls)
    cost_per_call_val = total_cost / max(1, total_calls)
    finops_score = max(0, 10 - round(cost_per_call_val / 0.001)) if total_calls > 0 else 1

    metrics = {
        "Revenue Impact": revenue_score,
        "Scalability": scalability_score,
        "Reusability": reusability_score,
        "Automation Impact": automation_score,
        "Knowledge Impact": knowledge_score,
        "Reliability": reliability_score,
        "Founder Independence": founder_score,
        "Operational Simplicity": simplicity_score,
        "Customer Value": customer_score,
        "FinOps Efficiency": finops_score,
    }
    total = sum(metrics.values())
    return total, metrics

current_total, current_metrics = compute_score(recent_events, finops_calls)

# Compare with last week's report if exists
last_week_total = None
last_week_file = None
try:
    five_days_ago = (datetime.now(timezone.utc) - timedelta(days=5)).strftime('%Y-%m-%d')
    all_reports = sorted(os.listdir("${REPORTS_DIR}")) if os.path.isdir("${REPORTS_DIR}") else []
    for rf in reversed(all_reports):
        if rf.startswith("weekly-") and rf != f"weekly-{report_date}.md":
            last_week_file = rf
            break
    if last_week_file:
        with open(os.path.join("${REPORTS_DIR}", last_week_file)) as f:
            for line in f:
                m = re.search(r'Enterprise Score:\s*(\d+)/100', line)
                if m:
                    last_week_total = int(m.group(1))
                    break
except (OSError, ValueError):
    pass

delta_str = ""
if last_week_total is not None:
    diff = current_total - last_week_total
    if diff > 0:
        delta_str = f" (+{diff} from last week)"
    elif diff < 0:
        delta_str = f" ({diff} from last week)"
    else:
        delta_str = " (no change from last week)"

report_lines.append(f"**Enterprise Score: {current_total}/100**{delta_str}")
status_emoji = "🟢 PASS" if current_total >= 60 else "🔴 FAIL"
report_lines.append(f"**Status**: {status_emoji} (threshold: ≥ 60)")
report_lines.append("")
report_lines.append("| Metric | Score |")
report_lines.append("|--------|-------|")
for name, score in current_metrics.items():
    bar = "█" * score + "░" * (10 - score)
    report_lines.append(f"| {name} | {bar} {score}/10 |")
report_lines.append("")
report_lines.append("---")
report_lines.append("")

# ── 2. Service Health ──────────────────────────────────
report_lines.append("## 2. Service Health")
report_lines.append("")

health_events = [e for e in recent_events if e.get("event") in ("service_healthy", "service_down", "service_recovered")]
total_health_checks = len([e for e in health_events if e.get("event") == "service_healthy"])
total_down_events = len([e for e in health_events if e.get("event") == "service_down"])
total_recovered = len([e for e in health_events if e.get("event") == "service_recovered"])
total_incidents = total_down_events

total_checks = total_health_checks + total_down_events
uptime_pct = round(total_health_checks / max(1, total_checks) * 100, 2) if total_checks > 0 else 100.0

report_lines.append(f"- **Uptime**: {uptime_pct}%")
report_lines.append(f"- **Health Checks**: {total_checks}")
report_lines.append(f"- **Downtime Events**: {total_down_events}")
report_lines.append(f"- **Recoveries**: {total_recovered}")
report_lines.append(f"- **Open Incidents**: {max(0, total_incidents - total_recovered)}")
report_lines.append("")
report_lines.append("---")
report_lines.append("")

# ── 3. FinOps Summary ──────────────────────────────────
report_lines.append("## 3. FinOps Summary")
report_lines.append("")

total_calls = len(finops_calls)
total_cost = sum(c.get("cost", 0) for c in finops_calls)
total_tokens = sum(c.get("total_tokens", 0) for c in finops_calls)
cost_per_call = round(total_cost / max(1, total_calls), 6)

report_lines.append(f"- **Total Calls**: {total_calls}")
report_lines.append(f"- **Total Cost**: \${total_cost:.6f}")
report_lines.append(f"- **Total Tokens**: {total_tokens}")
report_lines.append(f"- **Cost per Call**: \${cost_per_call}")
report_lines.append("")

# Model breakdown
model_stats = defaultdict(lambda: {"calls": 0, "cost": 0.0, "tokens": 0})
for c in finops_calls:
    m = c.get("model", "unknown")
    model_stats[m]["calls"] += 1
    model_stats[m]["cost"] += c.get("cost", 0)
    model_stats[m]["tokens"] += c.get("total_tokens", 0)

if model_stats:
    report_lines.append("| Model | Calls | Cost | Tokens |")
    report_lines.append("|-------|-------|------|--------|")
    for m, stats in sorted(model_stats.items()):
        report_lines.append(f"| {m} | {stats['calls']} | \${stats['cost']:.6f} | {stats['tokens']} |")
report_lines.append("")
report_lines.append("---")
report_lines.append("")

# ── 4. Skill Activity ──────────────────────────────────
report_lines.append("## 4. Skill Activity")
report_lines.append("")

skill_events = [e for e in recent_events if e.get("event") == "skill_execution"]
skill_counts = Counter()
skill_pass = Counter()
skill_fail = Counter()

for se in skill_events:
    p = se.get("payload", {})
    if isinstance(p, dict):
        skill_name = p.get("skill", se.get("producer", "unknown"))
    else:
        skill_name = se.get("producer", "unknown")
    status = p.get("status", "unknown") if isinstance(p, dict) else "unknown"
    skill_counts[skill_name] += 1
    if status == "pass":
        skill_pass[skill_name] += 1
    elif status == "fail":
        skill_fail[skill_name] += 1

if skill_counts:
    report_lines.append("| Skill | Runs | Pass | Fail | Pass Rate |")
    report_lines.append("|-------|------|------|------|-----------|")
    for skill_name in sorted(skill_counts):
        total_runs = skill_counts[skill_name]
        passed = skill_pass[skill_name]
        failed = skill_fail[skill_name]
        rate = round(passed / max(1, total_runs) * 100, 1)
        report_lines.append(f"| {skill_name} | {total_runs} | {passed} | {failed} | {rate}% |")
else:
    report_lines.append("No skill executions recorded in the last 7 days.")
report_lines.append("")
report_lines.append("---")
report_lines.append("")

# ── 5. Initiatives Report ──────────────────────────────
report_lines.append("## 5. Initiatives Report")
report_lines.append("")

initiative_dir = "${INITIATIVES_DIR}"
initiatives = []
if os.path.isdir(initiative_dir):
    for fname in sorted(os.listdir(initiative_dir)):
        if fname.endswith(".md") and fname not in ("REGISTRY.md", "initiative-TEMPLATE.md"):
            fpath = os.path.join(initiative_dir, fname)
            with open(fpath) as f:
                content = f.read()
            name_match = re.search(r'# Initiative:\s*(.+?)(?:\n|$)', content)
            initiative_name = name_match.group(1).strip() if name_match else fname.replace(".md", "")
            score_match = re.search(r'\*\*Total Score:\s*(\d+)/100', content)
            initiative_score = int(score_match.group(1)) if score_match else 0
            deadline_match = re.search(r'Deadline:\s*(\d{4}-\d{2}-\d{2})', content)
            deadline_str = deadline_match.group(1) if deadline_match else ""
            days_remaining = ""
            if deadline_str:
                try:
                    deadline_dt = datetime.strptime(deadline_str, "%Y-%m-%d").replace(tzinfo=timezone.utc)
                    remaining = (deadline_dt - now).days
                    if remaining > 0:
                        days_remaining = f"{remaining} days"
                    elif remaining == 0:
                        days_remaining = "Due today"
                    else:
                        days_remaining = f"Overdue by {-remaining} days"
                except ValueError:
                    days_remaining = "Invalid date"
            initiatives.append((initiative_name, initiative_score, days_remaining))

if initiatives:
    report_lines.append("| Initiative | Score | Deadline | Days Remaining |")
    report_lines.append("|------------|-------|----------|----------------|")
    for name, score, days_left in initiatives:
        status_flag = "⚠️ " if score < 60 else "✅ "
        report_lines.append(f"| {status_flag}{name} | {score}/100 | | {days_left} |")
else:
    report_lines.append("No active initiatives found.")
report_lines.append("")
report_lines.append("---")
report_lines.append("")

# ── 6. Top Events ──────────────────────────────────────
report_lines.append("## 6. Top Events")
report_lines.append("")

event_type_counts = Counter(e.get("event", "unknown") for e in recent_events)
if event_type_counts:
    total_event_count = sum(event_type_counts.values())
    report_lines.append(f"**Total events (7d)**: {total_event_count}")
    report_lines.append("")
    report_lines.append("| Event Type | Count | % of Total |")
    report_lines.append("|------------|-------|------------|")
    for etype, count in event_type_counts.most_common(10):
        pct = round(count / total_event_count * 100, 1)
        report_lines.append(f"| {etype} | {count} | {pct}% |")
else:
    report_lines.append("No events recorded in the last 7 days.")
report_lines.append("")
report_lines.append("---")
report_lines.append("")

# ── 7. Recommendations ─────────────────────────────────
report_lines.append("## 7. Recommendations")
report_lines.append("")

recommendations = []

# If uptime < 99%
if uptime_pct < 99.0:
    recommendations.append("- **🔴 Infra Review**: Uptime is {:.2f}% (below 99%). Review service reliability and auto-recovery procedures.".format(uptime_pct))

# If cost per call > $0.01
if cost_per_call > 0.01:
    recommendations.append("- **🟡 Model Optimization**: Cost per call is \${:.6f} (above \$0.01). Consider switching to cheaper models or optimizing prompt lengths.".format(cost_per_call))

# If any initiative score < 60
low_score_initiatives = [name for name, score, _ in initiatives if score < 60]
if low_score_initiatives:
    for init_name in low_score_initiatives:
        recommendations.append(f"- **🔴 Kill Review**: Initiative \"{init_name}\" scores below 60. Evaluate whether to continue, kill, or restructure.")

# If no events in 24h
if not last_24h:
    recommendations.append("- **🔴 System Check**: No events recorded in the last 24 hours. Verify the event pipeline and autonomous.sh cron job are functioning.")

# Always include a positive if nothing critical
for x in range(len(recommendations)):
    report_lines.append(recommendations[x])

if not recommendations:
    report_lines.append("- **🟢 All Clear**: No critical issues detected. Continue monitoring.")
    # Add growth recommendations
    report_lines.append("- **💡 Growth Tip**: Review initiative registry for scale candidates (KEEP → SCALE).")
    report_lines.append("- **💡 Knowledge Tip**: Ensure all OS are wired to knowledge capture for continuity.")

report_lines.append("")
report_lines.append("---")
report_lines.append("")
report_lines.append(f"_Report auto-generated on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}_")

# Write the report
with open("${REPORT_FILE}", "w") as f:
    f.write("\n".join(report_lines) + "\n")

print(f"Report written: ${REPORT_FILE}")
print(f"Enterprise Score: {current_total}/100{delta_str}")
print(f"Events analyzed: {len(recent_events)} (7d), {len(last_24h)} (24h)")
print(f"FinOps calls: {total_calls}")
print(f"Skills executed: {len(skill_events)}")
print(f"Recommendations: {len(recommendations)}")
PYEOF
