"""Auto-Doc — Module 7 of Evolution Engine (HAS-008)
Auto-generates session documentation from Evolution state.
"""
from datetime import datetime
from pathlib import Path


REPO = Path(__file__).resolve().parent.parent


def generate(spec_id: str, title: str, tier: int, summary: str = "") -> str:
    date = datetime.now().strftime("%Y-%m-%d")
    docs_dir = REPO / "process" / "completed" / spec_id.lower().replace("spec-", "")
    docs_dir.mkdir(parents=True, exist_ok=True)

    content = f"""# {spec_id} — {title}

**Date:** {date}
**Tier:** {tier}
**Auto-generated by Evolution Engine (HAS-008)**

## Summary

{summary or "No summary provided."}

## Evolution State

- Score: See `evolution/scorecard.json`
- Proposals: See `evolution/proposals/`
- ADRs: See `evolution/adr/`
"""
    path = docs_dir / f"{spec_id}.md"
    path.write_text(content)
    return str(path)
