"""
Brain graph data — system architecture as interconnected nodes.
Separated from FastAPI route for testability.
"""

SYSTEM_GRAPH = {
    "nodes": [
        {
            "id": "jarvis-core",
            "group": "jarvis",
            "label": "JARVIS Core",
            "type": "orchestrator",
            "desc": "Orquestador central de agentes (15 agentes)",
        },
        {
            "id": "agent-orchestrator",
            "group": "jarvis",
            "label": "AgentOrchestrator",
            "type": "orchestrator",
            "desc": "Router de tareas a 15 agentes",
        },
        {
            "id": "harness",
            "group": "jarvis",
            "label": "SDD Harness",
            "type": "orchestrator",
            "desc": "Pipeline de fases: Research\u2192Apply\u2192Verify",
        },
        {
            "id": "engram",
            "group": "jarvis",
            "label": "Engram",
            "type": "memory",
            "desc": "Memoria contextual persistente (SQLite+FTS5)",
        },
        {
            "id": "neo4j",
            "group": "jarvis",
            "label": "Neo4j",
            "type": "database",
            "desc": "Base de datos de grafos para sesiones",
        },
        {
            "id": "qdrant",
            "group": "jarvis",
            "label": "Qdrant",
            "type": "database",
            "desc": "Base de datos vectorial para embeddings",
        },
        {
            "id": "verify",
            "group": "jarvis",
            "label": "Verificador SDD",
            "type": "tool",
            "desc": "Valida estructura SDD de 17/17 specs",
        },
        {
            "id": "registry",
            "group": "jarvis",
            "label": "Skill Registry",
            "type": "tool",
            "desc": "\u00cdndice JSON de 50 habilidades",
        },
        {
            "id": "web-ui",
            "group": "jarvis",
            "label": "Web UI",
            "type": "interface",
            "desc": "FastAPI + HTML/JS en puerto 5174",
        },
        {
            "id": "research-agent",
            "group": "jarvis",
            "label": "ResearchAgent",
            "type": "agent",
            "desc": "B\u00fasqueda y s\u00edntesis de informaci\u00f3n",
        },
        {
            "id": "memory-agent",
            "group": "jarvis",
            "label": "MemoryAgent",
            "type": "agent",
            "desc": "Gesti\u00f3n de memoria y contexto",
        },
        {
            "id": "code-agent",
            "group": "jarvis",
            "label": "CodeAgent",
            "type": "agent",
            "desc": "An\u00e1lisis y generaci\u00f3n de c\u00f3digo",
        },
        {
            "id": "review-agent",
            "group": "jarvis",
            "label": "ReviewAgent",
            "type": "agent",
            "desc": "Code review y validaci\u00f3n",
        },
        {
            "id": "explore-agent",
            "group": "jarvis",
            "label": "ExploreAgent",
            "type": "agent",
            "desc": "Exploraci\u00f3n de archivos y sistema",
        },
        {
            "id": "skill-agent",
            "group": "jarvis",
            "label": "SkillAgent",
            "type": "agent",
            "desc": "Ejecuci\u00f3n de habilidades MCP",
        },
        {
            "id": "spec-agent",
            "group": "jarvis",
            "label": "SpecAgent",
            "type": "agent",
            "desc": "Generaci\u00f3n de specs SDD",
        },
        {
            "id": "design-agent",
            "group": "jarvis",
            "label": "DesignAgent",
            "type": "agent",
            "desc": "Generaci\u00f3n de plan.md y tasks.md",
        },
        {
            "id": "apply-agent",
            "group": "jarvis",
            "label": "ApplyAgent",
            "type": "agent",
            "desc": "Ejecuci\u00f3n de tareas con registry",
        },
        {
            "id": "verify-agent",
            "group": "jarvis",
            "label": "VerifyAgent",
            "type": "agent",
            "desc": "Validaci\u00f3n de constituci\u00f3n y tests",
        },
        {
            "id": "archive-agent",
            "group": "jarvis",
            "label": "ArchiveAgent",
            "type": "agent",
            "desc": "Documentaci\u00f3n y almacenaje en Engram",
        },
        {
            "id": "jarvis",
            "group": "jarvis",
            "label": "JARVIS (El Cerebro)",
            "type": "user",
            "desc": "Sistema central de IA",
        },
        {
            "id": "hermes",
            "group": "hermes",
            "label": "Hermes Agent",
            "type": "orchestrator",
            "desc": "Agente de IA aut\u00f3nomo con tool use",
        },
        {
            "id": "hermes-api",
            "group": "hermes",
            "label": "Hermes API",
            "type": "api",
            "desc": "API Server en puerto 8000",
        },
        {
            "id": "hermes-gateway",
            "group": "hermes",
            "label": "Hermes Gateway",
            "type": "gateway",
            "desc": "Gateway de plataformas en puerto 8642",
        },
        {
            "id": "hermes-desktop",
            "group": "hermes",
            "label": "Hermes Desktop",
            "type": "interface",
            "desc": "App Electron con voz (Ctrl+B)",
        },
        {
            "id": "telegram",
            "group": "hermes",
            "label": "Telegram Bot",
            "type": "platform",
            "desc": "Bot de Telegram conectado",
        },
        {
            "id": "whatsapp",
            "group": "hermes",
            "label": "WhatsApp Bridge",
            "type": "platform",
            "desc": "Puente WhatsApp (QR pendiente)",
        },
        {
            "id": "n8n",
            "group": "hermes",
            "label": "n8n",
            "type": "automation",
            "desc": "36 workflows de automatizaci\u00f3n",
        },
        {
            "id": "openclaw",
            "group": "openclaw",
            "label": "OpenClaw Gateway",
            "type": "gateway",
            "desc": "Gateway de 55 skills en puerto 18789",
        },
        {
            "id": "openclaw-skills",
            "group": "openclaw",
            "label": "55 Skills",
            "type": "tool",
            "desc": "Browser, payments, social, media, AI",
        },
        {
            "id": "mcp-bridge",
            "group": "mcp",
            "label": "JARVIS MCP Bridge",
            "type": "protocol",
            "desc": "Puente stdio para Hermes",
        },
        {
            "id": "mcp-server",
            "group": "mcp",
            "label": "MCP Server",
            "type": "protocol",
            "desc": "Servidor FastMCP dockerizado",
        },
        {
            "id": "docker",
            "group": "infra",
            "label": "Docker",
            "type": "infra",
            "desc": "Neo4j, Qdrant, MCP, n8n",
        },
        {
            "id": "systemd",
            "group": "infra",
            "label": "Systemd",
            "type": "infra",
            "desc": "jarvis-ui, jarvis-core, hermes-webui",
        },
        {
            "id": "llm",
            "group": "infra",
            "label": "LLM (OpenRouter)",
            "type": "external",
            "desc": "DeepSeek v4 Flash",
        },
        {
            "id": "user",
            "group": "user",
            "label": "T\u00fa",
            "type": "user",
            "desc": "El operador del sistema",
        },
    ],
    "links": [
        {
            "source": "user",
            "target": "web-ui",
            "label": "Web UI (navegador)",
            "type": "http",
        },
        {
            "source": "user",
            "target": "hermes-desktop",
            "label": "Voz (Ctrl+B)",
            "type": "voice",
        },
        {
            "source": "jarvis",
            "target": "agent-orchestrator",
            "label": "orquesta",
            "type": "internal",
        },
        {
            "source": "jarvis",
            "target": "harness",
            "label": "gestiona pipeline",
            "type": "internal",
        },
        {
            "source": "agent-orchestrator",
            "target": "research-agent",
            "label": "rutea",
            "type": "internal",
        },
        {
            "source": "agent-orchestrator",
            "target": "memory-agent",
            "label": "rutea",
            "type": "internal",
        },
        {
            "source": "agent-orchestrator",
            "target": "code-agent",
            "label": "rutea",
            "type": "internal",
        },
        {
            "source": "agent-orchestrator",
            "target": "review-agent",
            "label": "rutea",
            "type": "internal",
        },
        {
            "source": "agent-orchestrator",
            "target": "explore-agent",
            "label": "rutea",
            "type": "internal",
        },
        {
            "source": "agent-orchestrator",
            "target": "skill-agent",
            "label": "rutea",
            "type": "internal",
        },
        {
            "source": "harness",
            "target": "spec-agent",
            "label": "fase spec",
            "type": "internal",
        },
        {
            "source": "harness",
            "target": "design-agent",
            "label": "fase design",
            "type": "internal",
        },
        {
            "source": "harness",
            "target": "apply-agent",
            "label": "fase apply",
            "type": "internal",
        },
        {
            "source": "harness",
            "target": "verify-agent",
            "label": "fase verify",
            "type": "internal",
        },
        {
            "source": "harness",
            "target": "archive-agent",
            "label": "fase archive",
            "type": "internal",
        },
        {
            "source": "engram",
            "target": "memory-agent",
            "label": "persiste contexto",
            "type": "memory",
        },
        {
            "source": "neo4j",
            "target": "memory-agent",
            "label": "grafos",
            "type": "database",
        },
        {
            "source": "qdrant",
            "target": "memory-agent",
            "label": "vectores",
            "type": "database",
        },
        {
            "source": "jarvis",
            "target": "mcp-bridge",
            "label": "expone MCP tools",
            "type": "mcp",
        },
        {
            "source": "mcp-bridge",
            "target": "hermes",
            "label": "stdio MCP",
            "type": "mcp",
        },
        {
            "source": "hermes",
            "target": "hermes-desktop",
            "label": "app escritorio",
            "type": "process",
        },
        {
            "source": "hermes",
            "target": "hermes-api",
            "label": "API REST",
            "type": "http",
        },
        {
            "source": "hermes",
            "target": "hermes-gateway",
            "label": "gateway",
            "type": "internal",
        },
        {
            "source": "hermes-gateway",
            "target": "telegram",
            "label": "conecta",
            "type": "messaging",
        },
        {
            "source": "hermes-gateway",
            "target": "whatsapp",
            "label": "conecta",
            "type": "messaging",
        },
        {"source": "hermes-api", "target": "n8n", "label": "workflows", "type": "http"},
        {
            "source": "jarvis",
            "target": "openclaw",
            "label": "unified_bridge.py",
            "type": "http",
        },
        {
            "source": "openclaw",
            "target": "openclaw-skills",
            "label": "55 skills",
            "type": "internal",
        },
        {
            "source": "skill-agent",
            "target": "mcp-server",
            "label": "ejecuta MCP",
            "type": "mcp",
        },
        {"source": "docker", "target": "neo4j", "label": "container", "type": "infra"},
        {"source": "docker", "target": "qdrant", "label": "container", "type": "infra"},
        {"source": "systemd", "target": "web-ui", "label": "servicio", "type": "infra"},
        {"source": "systemd", "target": "jarvis", "label": "servicio", "type": "infra"},
        {"source": "llm", "target": "jarvis", "label": "API", "type": "external"},
        {
            "source": "user",
            "target": "jarvis",
            "label": "centro del sistema",
            "type": "conceptual",
        },
        {
            "source": "user",
            "target": "hermes",
            "label": "voz/chat",
            "type": "conceptual",
        },
        {
            "source": "user",
            "target": "openclaw",
            "label": "skills externas",
            "type": "conceptual",
        },
        {
            "source": "hermes",
            "target": "jarvis",
            "label": "MCP bridge",
            "type": "conceptual",
        },
        {
            "source": "jarvis",
            "target": "hermes",
            "label": "procesa tareas",
            "type": "conceptual",
        },
        {
            "source": "jarvis",
            "target": "openclaw",
            "label": "delega skills",
            "type": "conceptual",
        },
        {
            "source": "openclaw",
            "target": "hermes",
            "label": "resultados",
            "type": "conceptual",
        },
    ],
}
